
server:
  port: 8083
spring:
  application:
    name: flight-service
  admin-service:
    service-name: admin-service
  datasource:
    url: jdbc:mysql://localhost/flightDb?useLegacyDatetimeCode=false&serverTimezone=Europe/Amsterdam&useSSL=false
    username: root
    password: 913389696@Ww
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka/

      instance:
        hostname: localhost

